kind: Service
apiVersion: v1
metadata:
  name: ecommerce-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 8889
        ---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: ecommerce 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce 
  template:
    metadata:
      labels:
        app: ecommerce 
    spec:
      containers:
        - name: ecommerce 
          image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          ports:
            - containerPort: 8888 
