apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: ecommerce
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          ports:
            - containerPort: 8888 
